version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: expense_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "python manage.py migrate && gunicorn expense_tracker.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      USE_POSTGRES: "1"
      POSTGRES_DB: expense_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
    depends_on:
      - db
volumes:
  postgres_data:
